---
title: "Project Codebook"
output: html_document
---

##Project Description
In this project, data collected from a group of 30 volunteers performing activities with the Samsung Galaxy S II smartphone were cleaned into a tidy data set.

##Study design and data processing
###Collection of raw data
The embedded accelerometer and gyroscope in the smartphone allowed for collection of 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz while the volunteers performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING). Data from the 30 volunteers were randomly split into test (9) and train (21) groups.
###Notes on original data
The sensor signals were processed considering gravitational force with sampling within a fixed width sliding window to generate a vector of 561 features. Each feature is normalized to be within [-1,1].

##Creating the tidy data file
###Guide to creating the tidy data file
Original data were downloaded; test and train data sets were read as data frames into R. Columns were appropriately renamed and data frames for test and train were each generated by combining the data sets. Test and train data were then merged.
Mean and Standard deviation variables were extracted by searching for the strings.
Numbers under the activity label column were replaced with descriptive labels (e.g. WALKING, LAYING). Numbers were searched and replaced. 
Column names were replaced with descriptive feature variable names from the features table. 
The data frame was lastly grouped by the subject and activity columns, and an average calculated for each variable. 
###Cleaning of the data
The run_analysis R script takes the original raw data and outputs a final clean data file with a table summarizing an average value for each mean and standard deviation feature variable for each test subject and each activity. Link to README:

##Description of the variables in the final tidy data text file
The final tidy data file is a data frame with 180 rows and 88 columns; Each row has the average values for each of the 86 variable features that are mean or standard deviation. Each row represents the data for one test subject for one activity.
###Notes on the variables
The first column is the identifier of the subjects (subject number); these are integers between 1 and 30.
The second column is the activity label; these are character strings.

The rest of the table are numeric feature variables where the variable names are abbreviated words combined together. 
- the first letter of the variables is either "t","f", or "a"; these stand for time, frequency and angle respectively.
- "Gyro" refers to data from the smartphone gyroscope & "Acc" refers to data from the smartphone accelerometer.
- the X, Y, or Z at the end of feature variable names refer to the axial direction in which the signal is recorded.
- "Jerk" stands for the jerk signals derived from body linear acceleration and angular velocity measured by the smartphone.
- "Mag" stands for Euclidean magnitude of the three-dimensional signals.
